package sri.web.template.components

import org.scalajs.dom
import sri.core.{ComponentP, CreateElement, ReactElement}
import sri.macros.web.styledtagsPrefix_<^._
import sri.web.template.components.HomeScreen.State
import sri.web.vdom.tags.ReactEventI

import scala.scalajs.js.annotation.ScalaJSDefined

@ScalaJSDefined
private class StyledTagsComTest extends ComponentP[StyledTagsComTest.Props] {
  override def render(): ReactElement = <.div(
    ^.className := "some",
    ^.value := "asdf"
  )(
    <.p()("This is generated by styled tags."),
    <.input(
      ^.onClick := onTextChange _,
      ^.value := props.getState().text
    )
  )

  def onTextChange(e: ReactEventI) = {
    val value = e.target.value
    dom.window.console.log(value)
    props.setState(props.getState().copy(text = value))
  }
}

private object StyledTagsComTest {
  case class Props(getState: () => State, setState: State => Unit)
  def apply(props: Props): ReactElement = CreateElement[StyledTagsComTest](props)
}